const express = require("express");
const cors = require("cors");
const helmet = require("helmet");

const app = express();

/* =========================
   SECURITY + MIDDLEWARE
========================= */

app.use(express.json());

app.use(cors({
  origin: "*",
  methods: ["GET", "POST"]
}));

app.use(helmet());

/* =========================
   FREE USER LIMIT SYSTEM
========================= */

let freeUsage = {};

/* =========================
   HOME ROUTE
========================= */

app.get("/", (req, res) => {

  res.json({
    success: true,
    message: "Skivlo Resume API Running",
    status: "online"
  });

});

/* =========================
   RESUME GENERATOR API
========================= */

app.post("/generate-resume", (req, res) => {

  try {

    const {
      name,
      skills,
      experience,
      plan
    } = req.body;

    /* =========================
       BASIC VALIDATION
    ========================= */

    if (!name || !skills || !experience) {

      return res.status(400).json({
        success: false,
        message: "All fields required"
      });

    }

    /* =========================
       FREE LIMIT LOGIC
    ========================= */

    const userIP = req.ip;

    if (!freeUsage[userIP]) {
      freeUsage[userIP] = 0;
    }

    if (plan !== "premium") {

      if (freeUsage[userIP] >= 2) {

        return res.status(403).json({
          success: false,
          upgrade: true,
          message: "Free limit reached",
          premiumBenefits: [
            "Unlimited resumes",
            "HD PDF export",
            "ATS optimized layout",
            "Professional formatting",
            "Faster generation"
          ]
        });

      }

      freeUsage[userIP]++;

    }

    /* =========================
       SMART PROFESSIONAL SUMMARY
    ========================= */

    let summary = "";

    if (plan === "premium") {

      summary =
        `Professional candidate with strong expertise in ${skills}. 
Experienced in delivering high-quality work with professional communication, advanced problem-solving abilities, and modern industry standards.`;

    } else {

      summary =
        `Skilled professional with experience in ${skills} and ability to deliver quality work efficiently.`;

    }

    /* =========================
       RESUME FORMATTING
    ========================= */

    const resume = `
========================================
${name.toUpperCase()}
========================================

PROFESSIONAL SUMMARY
${summary}

----------------------------------------

CORE SKILLS
${skills}

----------------------------------------

WORK EXPERIENCE
${experience}

----------------------------------------

Resume Generated By Skivlo AI Resume Builder
Plan: ${plan === "premium" ? "Premium" : "Free"}

`;

    /* =========================
       RESPONSE
    ========================= */

    res.json({

      success: true,

      plan: plan === "premium" ? "premium" : "free",

      remainingFreeUses:
        plan === "premium"
          ? "Unlimited"
          : 2 - freeUsage[userIP],

      features:
        plan === "premium"
          ? [
              "HD PDF",
              "ATS Resume",
              "Professional Formatting",
              "Unlimited Usage",
              "Fast Generation"
            ]
          : [
              "Basic Resume",
              "Normal PDF",
              "2 Free Uses Daily"
            ],

      resume: resume

    });

  } catch (error) {

    res.status(500).json({
      success: false,
      message: "Server Error"
    });

  }

});

/* =========================
   SERVER START
========================= */

const PORT = process.env.PORT || 3000;

app.listen(PORT, () => {

  console.log(`Server running on port ${PORT}`);

});
